name: Download Google Drive Folder

on:
  workflow_dispatch:
    inputs:
      folder_url:
        description: 'Google Drive Folder URL'
        required: true
        type: string
      zipfile_name:
        description: 'Final Zip File Name'
        required: true
        type: string

jobs:
  download-and-upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install gdown telethon
        sudo apt-get install unzip -y

    - name: Download Google Drive folder
      run: |
        gdown "${{ github.event.inputs.folder_url }}" -O ./gdrive-files --folder

    - name: Compress downloaded files
      run: |
        zip -s 2000m -r "${{ inputs.zipfile_name }}.zip" gdrive-files/

    - name: Upload all ZIP parts to Telegram
      env:
        TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
        TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
        TELEGRAM_SESSION: ${{ secrets.TELEGRAM_SESSION }}
      run: |
        # Get base name from input
        BASE_NAME="${{ inputs.zipfile_name }}"
        
        # Create an array of matching files
        files=("$BASE_NAME".z*)
        
        echo "🔍 Found files:"
        printf "  %s\n" "${files[@]}"
        
        # Early exit if no files
        if [ ${#files[@]} -eq 0 ]; then
          echo "❌ No ZIP part files found for base name '$BASE_NAME'"
          exit 1
        fi
        
        # Upload each file
        for file in "${files[@]}"; do
          if [ -f "$file" ]; then
            echo "📤 Uploading: $file"
            python tg-upload.py "$file"
          else
            echo "⚠️ File not found or invalid name: $file"
          fi
        done
